services:
  - type: web
    name: ml-prediction-service-rudhra
    env: python
    buildCommand: pip install -r requirements.txt && python train_save_model.py
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
